[package]
name = "sdf-play"
version = "0.1.0"
authors = ["Srinivas Kaza <srinivas@kaza.io>"]

[dependencies]
notify = "4.0.0"
nalgebra-glm = "0.1"
conrod = { version = "0.55.0", features = ["glium", "winit"] }
find_folder = "*"